config:
  rsocket:
    port: 3000
    delay: 100
    socket_timeout: 60
    capt_timeout: 5
    solve_timeout: 10
    recipe_timeout: 3
    protocol: protocol of the robot controller
    update_frame_id: the frame r_socket.js will update, the alternative of ROS driver
    source_frame_id: the frame where master is placed
    target_frame_id: the frame solved
    base_frame_id: the frame to see the transform between source->target
